In [1]:
import pandas as pd
import os

In [ ]:
RAW_DATA_PATH = os.path.join("..", "data", "raw")

profile_data = pd.read_csv(os.path.join(RAW_DATA_PATH, 'profile_data.csv'))
activity_logs = pd.read_csv(os.path.join(RAW_DATA_PATH, 'activity_logs.csv'))
trip_logs = pd.read_csv(os.path.join(RAW_DATA_PATH, 'trip_logs.csv'))
incentive_logs = pd.read_csv(os.path.join(RAW_DATA_PATH, 'incentive_logs.csv'))
interaction_logs = pd.read_csv(os.path.join(RAW_DATA_PATH, 'interaction_logs.csv'))

In [3]:
display(profile_data.head())
display(activity_logs.head())
display(trip_logs.head())
display(incentive_logs.head())
display(interaction_logs.head())

,driver_id,signup_date,vehicle_dispatchability,avg_rating,current_tier,Churned
0,5729981b-bf65-48ac-a418-95693a8d26ef,2025-07-16T12:43:42.076226+00:00,{UberX},4.84,Blue,0
1,caf9988b-9ff9-4dcc-b9a5-4d6953ac8a0b,2025-11-04T07:36:10.076226+00:00,"{UberX,Comfort,Electric}",4.80,Platinum,0
2,5d9761b2-ee05-4923-98ca-1f16a4a6df73,2025-06-27T07:06:08.076226+00:00,"{UberBlack,Premier,Comfort,UberX}",4.91,Diamond,0
3,0a298bab-317f-49f7-a021-432c6cf80366,2025-10-19T02:08:13.076226+00:00,"{UberBlack,Premier,Comfort,UberX}",4.94,Platinum,0
4,5843b2fc-ffa0-4cd2-a0bc-c950eecab4f0,2025-08-14T05:17:21.076226+00:00,{UberX},4.72,Blue,1

,session_id,driver_id,session_start,session_end
0,1,5729981b-bf65-48ac-a418-95693a8d26ef,2025-07-22T15:19:45.076226+00:00,2025-07-22T20:15:10.544158+00:00
1,2,5729981b-bf65-48ac-a418-95693a8d26ef,2025-10-05T13:40:41.076226+00:00,2025-10-05T20:36:19.683734+00:00
2,3,5729981b-bf65-48ac-a418-95693a8d26ef,2025-08-05T05:06:13.076226+00:00,2025-08-05T08:38:14.135128+00:00
3,4,5729981b-bf65-48ac-a418-95693a8d26ef,2025-10-05T22:13:08.076226+00:00,2025-10-06T02:10:36.503861+00:00
4,5,5729981b-bf65-48ac-a418-95693a8d26ef,2025-09-17T01:48:19.076226+00:00,2025-09-17T06:57:02.909186+00:00

,trip_id,driver_id,request_time,pickup_time,trip_duration_seconds,fare,tip,surge_multiplier,pickup_lat,pickup_long,dropoff_lat,dropoff_long,trip_type
0,1,5729981b-bf65-48ac-a418-95693a8d26ef,2025-07-22T15:34:45.076226+00:00,2025-07-22T15:37:45.076226+00:00,960,6.67,0.0,1.0,43.645536,-79.394757,43.616448,-79.720831,UberX
1,2,5729981b-bf65-48ac-a418-95693a8d26ef,2025-07-22T16:15:45.076226+00:00,2025-07-22T16:22:45.076226+00:00,1620,11.25,0.0,1.0,43.660780,-79.767113,43.586540,-79.794773,UberX
2,3,5729981b-bf65-48ac-a418-95693a8d26ef,2025-07-22T17:32:45.076226+00:00,2025-07-22T17:41:45.076226+00:00,2160,19.50,0.0,1.0,43.824188,-79.405598,43.669134,-79.244326,Comfort
3,4,5729981b-bf65-48ac-a418-95693a8d26ef,2025-07-22T18:23:45.076226+00:00,2025-07-22T18:30:45.076226+00:00,1980,13.75,0.0,1.0,43.619877,-79.779394,43.683656,-79.449860,UberX
4,5,5729981b-bf65-48ac-a418-95693a8d26ef,2025-10-05T13:55:41.076226+00:00,2025-10-05T14:03:41.076226+00:00,1740,12.08,0.0,1.0,43.841933,-79.814819,43.903923,-79.719360,UberX

,incentive_id,driver_id,incentive_type,offer_date,status,bonus_amount
0,1,5729981b-bf65-48ac-a418-95693a8d26ef,Quest,2025-10-10T02:40:37.076226+00:00,offered,0.0
1,2,5729981b-bf65-48ac-a418-95693a8d26ef,Quest,2025-11-07T03:03:03.076226+00:00,offered,0.0
2,3,5729981b-bf65-48ac-a418-95693a8d26ef,Quest,2025-07-21T05:15:05.076226+00:00,offered,0.0
3,4,5729981b-bf65-48ac-a418-95693a8d26ef,Quest,2025-08-11T16:29:02.076226+00:00,offered,0.0
4,5,5729981b-bf65-48ac-a418-95693a8d26ef,Quest,2025-11-21T18:54:22.076226+00:00,offered,0.0

,event_id,driver_id,event_timestamp,event_type
0,1,5729981b-bf65-48ac-a418-95693a8d26ef,2025-07-22T18:21:27.076226+00:00,heatmap_view
1,2,5729981b-bf65-48ac-a418-95693a8d26ef,2025-07-22T18:36:07.076226+00:00,app_open
2,3,5729981b-bf65-48ac-a418-95693a8d26ef,2025-07-22T19:40:05.076226+00:00,destination_set
3,4,5729981b-bf65-48ac-a418-95693a8d26ef,2025-07-22T17:40:35.076226+00:00,heatmap_view
4,5,5729981b-bf65-48ac-a418-95693a8d26ef,2025-07-22T15:34:45.076226+00:00,trip_accepted

In [4]:
profile_data['Churned'].value_counts(normalize=True)

Churned
0    0.688468
1    0.311532
Name: proportion, dtype: float64

In [5]:
df_list = [profile_data, activity_logs, trip_logs, incentive_logs, interaction_logs]

for df_name in df_list:
    display(df_name.dtypes)

driver_id                   object
signup_date                 object
vehicle_dispatchability     object
avg_rating                 float64
current_tier                object
Churned                      int64
dtype: object

session_id        int64
driver_id        object
session_start    object
session_end      object
dtype: object

trip_id                    int64
driver_id                 object
request_time              object
pickup_time               object
trip_duration_seconds      int64
fare                     float64
tip                      float64
surge_multiplier         float64
pickup_lat               float64
pickup_long              float64
dropoff_lat              float64
dropoff_long             float64
trip_type                 object
dtype: object

incentive_id        int64
driver_id          object
incentive_type     object
offer_date         object
status             object
bonus_amount      float64
dtype: object

event_id            int64
driver_id          object
event_timestamp    object
event_type         object
dtype: object

In [6]:
for df_name in df_list:
    display(df_name.isnull().sum())

driver_id                  0
signup_date                0
vehicle_dispatchability    0
avg_rating                 0
current_tier               0
Churned                    0
dtype: int64

session_id       0
driver_id        0
session_start    0
session_end      0
dtype: int64

trip_id                  0
driver_id                0
request_time             0
pickup_time              0
trip_duration_seconds    0
fare                     0
tip                      0
surge_multiplier         0
pickup_lat               0
pickup_long              0
dropoff_lat              0
dropoff_long             0
trip_type                0
dtype: int64

incentive_id      0
driver_id         0
incentive_type    0
offer_date        0
status            0
bonus_amount      0
dtype: int64

event_id           0
driver_id          0
event_timestamp    0
event_type         0
dtype: int64

In [7]:
for df_name in df_list: 
    display(df_name.describe())

       avg_rating     Churned
count  581.000000  581.000000
mean     4.829793    0.311532
std      0.105952    0.463519
min      4.500000    0.000000
25%      4.770000    0.000000
50%      4.840000    0.000000
75%      4.910000    1.000000
max      5.000000    1.000000

         session_id
count  59225.000000
mean   29613.000000
std    17096.929183
min        1.000000
25%    14807.000000
50%    29613.000000
75%    44419.000000
max    59225.000000

,trip_id,trip_duration_seconds,fare,tip,surge_multiplier,pickup_lat,pickup_long,dropoff_lat,dropoff_long
count,522888.000000,522888.000000,522888.000000,522888.000000,522888.000000,522888.000000,522888.000000,522888.000000,522888.000000
mean,261444.500000,1565.554689,16.922998,0.779664,1.229459,43.765357,-79.500149,43.765071,-79.500444
std,150944.908116,659.656354,12.862185,2.019117,0.505652,0.106807,0.231289,0.106787,0.230870
min,1.000000,480.000000,3.330000,0.000000,1.000000,43.580000,-79.900000,43.580000,-79.900000
25%,130722.750000,960.000000,8.750000,0.000000,1.000000,43.672855,-79.700529,43.672608,-79.700417
50%,261444.500000,1560.000000,14.080000,0.000000,1.000000,43.765615,-79.500529,43.765093,-79.500999
75%,392166.250000,2160.000000,19.870000,0.000000,1.000000,43.857731,-79.299930,43.857561,-79.300895
max,522888.000000,2700.000000,166.500000,39.290000,3.000000,43.950000,-79.100001,43.950000,-79.100001

       incentive_id  bonus_amount
count  15228.000000  15228.000000
mean    7614.500000     46.851975
std     4396.089285     56.838080
min        1.000000      0.000000
25%     3807.750000      1.000000
50%     7614.500000      1.000000
75%    11421.250000    104.800000
max    15228.000000    149.990000

           event_id
count  1.227850e+06
mean   6.139255e+05
std    3.544499e+05
min    1.000000e+00
25%    3.069632e+05
50%    6.139255e+05
75%    9.208878e+05
max    1.227850e+06

In [8]:
print("="*50)
print("Checking activity_logs: session_end vs. session_start...")

# Find all rows where the end time is on or before the start time
invalid_sessions = activity_logs[activity_logs['session_end'] <= activity_logs['session_start']]

if len(invalid_sessions) == 0:
    print("PASS: All sessions have an end time after their start time.")
else:
    print(f"FAIL: Found {len(invalid_sessions)} sessions where session_end is NOT after session_start.")
    print("Here are some examples:")
    display(invalid_sessions.head())

print("="*50)
print("\n")

==================================================
Checking activity_logs: session_end vs. session_start...
PASS: All sessions have an end time after their start time.
==================================================

In [10]:
print("="*50)
print("Checking trip_logs: pickup_time vs. request_time...")

# Find all rows where the pickup time is on or before the request time
invalid_trips = trip_logs[trip_logs['pickup_time'] <= trip_logs['request_time']]

if len(invalid_trips) == 0:
    print("PASS: All trips have a pickup time after their request time.")
else:
    print(f"FAIL: Found {len(invalid_trips)} trips where pickup_time is NOT after request_time.")
    print("Here are some examples:")
    display(invalid_trips.head())

print("="*50)

==================================================
Checking trip_logs: pickup_time vs. request_time...
PASS: All trips have a pickup time after their request time.
==================================================

In [11]:
actual_tiers = set(profile_data['current_tier'].dropna().unique())
expected_tiers = {"Blue", "Gold", "Platinum", "Diamond"}

print("="*50)
print(f"Expected Tiers: {expected_tiers}")
print(f"Actual Tiers Found: {actual_tiers}")
print("="*50)

==================================================
Expected Tiers: {'Blue', 'Gold', 'Platinum', 'Diamond'}
Actual Tiers Found: {'Blue', 'Gold', 'Platinum', 'Diamond'}
==================================================

In [12]:
unique_trip_types = trip_logs['trip_type'].dropna().str.strip().unique()
expected_trip_types = {"UberX", "UberBlack", "Premier", "Comfort", "Electric"}

print("="*50)
print(f"Expected Trip Types: {expected_trip_types}")
print(f"Actual Trip Types: {unique_trip_types}")
print("="*50)

==================================================
Expected Trip Types: {'UberX', 'UberBlack', 'Electric', 'Premier', 'Comfort'}
Actual Trip Types: ['UberX' 'Comfort' 'Electric' 'Premier' 'UberBlack']
==================================================

In [13]:
unique_event_types = interaction_logs['event_type'].unique()
expected_event_types={'app_open', 'destination_set', 'heatmap_view', 'trip_accepted', 'trip_cancelled', 'trip_ignored'}

print("="*50)
print(f"Expected Trip Types: {expected_event_types}")
print(f"Actual Trip Types: {unique_event_types}")
print("="*50)

==================================================
Expected Trip Types: {'trip_ignored', 'trip_accepted', 'destination_set', 'app_open', 'trip_cancelled', 'heatmap_view'}
Actual Trip Types: ['heatmap_view' 'app_open' 'destination_set' 'trip_accepted'
 'trip_ignored' 'trip_cancelled']
==================================================